# Generated by Django 5.1.1 on 2024-09-24 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Neutral"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ]
                    ),
                ),
                (
                    "productivity_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Average"),
                            (4, "High"),
                            (5, "Very High"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "working_day",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="working_day_date_feb082_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "importance",
                    models.IntegerField(
                        choices=[
                            (1, "Most important task of the day"),
                            (2, "Secondary tasks of importance"),
                            (3, "Additional tasks"),
                        ]
                    ),
                ),
                (
                    "estimate",
                    models.IntegerField(
                        choices=[
                            (1, "1 Pomodoro"),
                            (2, "2 Pomodoros"),
                            (3, "3 Pomodoros"),
                            (4, "4 Pomodoros"),
                            (5, "5 Pomodoros"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "working_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="planner.workingday",
                    ),
                ),
            ],
            options={
                "db_table": "task",
                "ordering": ["-importance"],
                "indexes": [
                    models.Index(fields=["-importance"], name="task_importa_cccbf5_idx")
                ],
            },
        ),
    ]
