name: Django CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_and_typecheck:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER || 'postgres' }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'postgres' }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB || 'test_db' }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${{ secrets.POSTGRES_DB || 'test_db' }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER || 'postgres' }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'postgres' }}
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${{ secrets.POSTGRES_DB || 'test_db' }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER || 'postgres' }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'postgres' }}
      run: |
        python manage.py test

    - name: Run mypy
      run: |
        mypy .

    # Force GitHub Actions to use Node.js 20 for all JavaScript actions
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true